name: Push to trust

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checks out cylibs
        run:  ./generate_folders.sh
        
      - name: Pushes cylibs to trust
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'temp'
          destination-github-username: 'cyritegamestudios'
          destination-repository-name: 'trust'
          target-directory: 'addons/libs/cylibs'
          commit-message: 'Automated commit to update cylibs'
          target-branch: main
