name: Push to staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checks out cylibs
        run:  ./generate_folders.sh
        
      - name: Pushes cylibs to staging
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: staging
          FOLDER: 'temp'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Automated commit to update cylibs on staging"
